//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public int TOUR_ID { get; set; }
        public string TOUR_NAME { get; set; }
        public string PLACE { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
    }
}
