//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        public decimal TOUR_ID { get; set; }
        public string TOUR_NAME { get; set; }
        public string PLACE { get; set; }
        public decimal DAYS { get; set; }
        public decimal PRICE { get; set; }
        public string LOCATIONS { get; set; }
        public string TOUR_INFO { get; set; }
        public string pic { get; set; }
    }
}
